### Variables

# Name
name: persistence-oss

# Port
port: 8080

# Replicas
replicas: 1

# Resources
resources:
  # Limits
  limits:
    # CPU
    cpu: 800m
    # Memory
    memory: 1000Mi

# Kafka
kafka:
  address: "kafka.apps.svc.cluster.local:9092"
  topic: "create"
  groupId: "persistence"

# Endpoints
endpoints:
  # OTel collector
  otelcollector: "http://otel-collector-collector.monitoring.svc.cluster.local:4317"

# MySQL
mysql:
  server: ""
  # Username
  username: "root"
  # Password
  password: ""
  # Port
  port: 3306
  # Database
  database: ""
