### Variables

# Name
name: persistence-nr

# Port
port: 8080

# Replicas
replicas: 1

# Resources
resources:
  # Limits
  limits:
    # CPU
    cpu: 800m
    # Memory
    memory: 1000Mi

# Kafka
kafka:
  # Address
  address: "kafka.apps.svc.cluster.local:9092"
  # Topic
  topic: "create"
  # Consumer group ID
  groupId: "persistence"

# New Relic
newrelic:
  # Application name
  appName: persistence-nr
  # License key
  licenseKey: ""

# MySQL
mysql:
  server: ""
  # Username
  username: "root"
  # Password
  password: ""
  # Port
  port: 3306
  # Database
  database: ""
