### Variables

# Name
name: proxy-oss

# Port
port: 8080

# Replicas
replicas: 1

# Resources
resources:
  # Limits
  limits:
    # CPU
    cpu: 800m
    # Memory
    memory: 1000Mi

# Endpoints
endpoints:
  # OTel collector
  otelcollector: "http://otel-collector-collector.monitoring.svc.cluster.local:4317"
  # Persistence service
  persistence: "http://persistence-oss.apps.svc.cluster.local:8080/persistence"
