apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.dockerhubName }}/{{ .Values.imageName }}"
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: {{ .Values.port }}
          resources:
            limits:
              cpu: 400m
              memory: 1000Mi
