apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Values.name }}
spec:
  exporter:
    endpoint: {{ .Values.endpoint }}
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  java:
        